<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use App\Models\Permission;

class UpdatePermissionNames extends Command
{
    protected $signature   = 'permissions:update-names';
    protected $description = 'Fill name_ar and name_en for all permissions based on their title';

    // ────────────────────────────────────────────────────────────────────────
    // Full name map  title => [ar, en]
    // ────────────────────────────────────────────────────────────────────────
    private array $map = [
        // ── User Management (cat 1) ──────────────────────────────────────────
        'user_management_access'      => ['إدارة المستخدمين',           'User Management'],
        'permission_create'           => ['إضافة صلاحية',               'Create Permission'],
        'permission_edit'             => ['تعديل صلاحية',               'Edit Permission'],
        'permission_show'             => ['عرض صلاحية',                 'Show Permission'],
        'permission_delete'           => ['حذف صلاحية',                 'Delete Permission'],
        'permission_access'           => ['الوصول للصلاحيات',          'Access Permissions'],
        'role_create'                 => ['إضافة دور',                  'Create Role'],
        'role_edit'                   => ['تعديل دور',                  'Edit Role'],
        'role_show'                   => ['عرض دور',                    'Show Role'],
        'role_delete'                 => ['حذف دور',                    'Delete Role'],
        'role_access'                 => ['الوصول للأدوار',             'Access Roles'],
        'user_create'                 => ['إضافة مستخدم',               'Create User'],
        'user_edit'                   => ['تعديل مستخدم',               'Edit User'],
        'user_show'                   => ['عرض مستخدم',                 'Show User'],
        'user_delete'                 => ['حذف مستخدم',                 'Delete User'],
        'user_access'                 => ['الوصول للمستخدمين',         'Access Users'],
        'user_status_create'          => ['إضافة حالة مستخدم',         'Create User Status'],
        'user_status_edit'            => ['تعديل حالة مستخدم',         'Edit User Status'],
        'user_status_show'            => ['عرض حالة مستخدم',           'Show User Status'],
        'user_status_delete'          => ['حذف حالة مستخدم',           'Delete User Status'],
        'user_status_access'          => ['الوصول لحالات المستخدمين',  'Access User Statuses'],
        // ── Slide Shows (cat 2) ──────────────────────────────────────────────
        'slide_show_create'           => ['إضافة شريحة عرض',           'Create Slide Show'],
        'slide_show_edit'             => ['تعديل شريحة عرض',           'Edit Slide Show'],
        'slide_show_show'             => ['عرض شريحة عرض',             'Show Slide Show'],
        'slide_show_delete'           => ['حذف شريحة عرض',             'Delete Slide Show'],
        'slide_show_access'           => ['الوصول لشرائح العرض',       'Access Slide Shows'],
        // ── Restaurants (cat 3) ──────────────────────────────────────────────
        'restaurant_create'           => ['إضافة مطعم',                'Create Restaurant'],
        'restaurant_edit'             => ['تعديل مطعم',                'Edit Restaurant'],
        'restaurant_show'             => ['عرض مطعم',                  'Show Restaurant'],
        'restaurant_delete'           => ['حذف مطعم',                  'Delete Restaurant'],
        'restaurant_access'           => ['الوصول للمطاعم',            'Access Restaurants'],
        'restaurants_management_access'=> ['إدارة المطاعم',            'Restaurants Management'],
        'category_create'             => ['إضافة تصنيف',               'Create Category'],
        'category_edit'               => ['تعديل تصنيف',               'Edit Category'],
        'category_show'               => ['عرض تصنيف',                 'Show Category'],
        'category_delete'             => ['حذف تصنيف',                 'Delete Category'],
        'category_access'             => ['الوصول للتصنيفات',          'Access Categories'],
        'item_create'                 => ['إضافة منتج',                'Create Item'],
        'item_edit'                   => ['تعديل منتج',                'Edit Item'],
        'item_show'                   => ['عرض منتج',                  'Show Item'],
        'item_delete'                 => ['حذف منتج',                  'Delete Item'],
        'item_access'                 => ['الوصول للمنتجات',           'Access Items'],
        'extra_create'                => ['إضافة إضافة',               'Create Extra'],
        'extra_edit'                  => ['تعديل إضافة',               'Edit Extra'],
        'extra_show'                  => ['عرض إضافة',                 'Show Extra'],
        'extra_delete'                => ['حذف إضافة',                 'Delete Extra'],
        'extra_access'                => ['الوصول للإضافات',           'Access Extras'],
        // ── Delivery (cat 4) ─────────────────────────────────────────────────
        'delivery_create'             => ['إضافة توصيل',               'Create Delivery'],
        'delivery_edit'               => ['تعديل توصيل',               'Edit Delivery'],
        'delivery_show'               => ['عرض توصيل',                 'Show Delivery'],
        'delivery_delete'             => ['حذف توصيل',                 'Delete Delivery'],
        'delivery_access'             => ['الوصول للتوصيل',            'Access Delivery'],
        'delivery_company_create'     => ['إضافة شركة توصيل',          'Create Delivery Company'],
        'delivery_company_edit'       => ['تعديل شركة توصيل',          'Edit Delivery Company'],
        'delivery_company_show'       => ['عرض شركة توصيل',            'Show Delivery Company'],
        'delivery_company_delete'     => ['حذف شركة توصيل',            'Delete Delivery Company'],
        'delivery_company_access'     => ['الوصول لشركات التوصيل',     'Access Delivery Companies'],
        'delivery_management_access'  => ['إدارة التوصيل',             'Delivery Management'],
        // ── Orders (cat 5) ───────────────────────────────────────────────────
        'order_create'                => ['إضافة طلب',                 'Create Order'],
        'order_edit'                  => ['تعديل طلب',                 'Edit Order'],
        'order_show'                  => ['عرض طلب',                   'Show Order'],
        'order_delete'                => ['حذف طلب',                   'Delete Order'],
        'order_access'                => ['الوصول للطلبات',            'Access Orders'],
        'order_mangement_access'      => ['إدارة الطلبات',             'Order Management'],
        'order_type_create'           => ['إضافة نوع طلب',             'Create Order Type'],
        'order_type_edit'             => ['تعديل نوع طلب',             'Edit Order Type'],
        'order_type_show'             => ['عرض نوع طلب',               'Show Order Type'],
        'order_type_delete'           => ['حذف نوع طلب',               'Delete Order Type'],
        'order_type_access'           => ['الوصول لأنواع الطلبات',     'Access Order Types'],
        'order_status_create'         => ['إضافة حالة طلب',            'Create Order Status'],
        'order_status_edit'           => ['تعديل حالة طلب',            'Edit Order Status'],
        'order_status_show'           => ['عرض حالة طلب',              'Show Order Status'],
        'order_status_delete'         => ['حذف حالة طلب',              'Delete Order Status'],
        'order_status_access'         => ['الوصول لحالات الطلبات',     'Access Order Statuses'],
        'cansel_reason_create'        => ['إضافة سبب إلغاء',           'Create Cancel Reason'],
        'cansel_reason_edit'          => ['تعديل سبب إلغاء',           'Edit Cancel Reason'],
        'cansel_reason_show'          => ['عرض سبب إلغاء',             'Show Cancel Reason'],
        'cansel_reason_delete'        => ['حذف سبب إلغاء',             'Delete Cancel Reason'],
        'cansel_reason_access'        => ['الوصول لأسباب الإلغاء',     'Access Cancel Reasons'],
        // ── Payments & Subscriptions (cat 6) ─────────────────────────────────
        'payment_method_create'       => ['إضافة طريقة دفع',           'Create Payment Method'],
        'payment_method_edit'         => ['تعديل طريقة دفع',           'Edit Payment Method'],
        'payment_method_show'         => ['عرض طريقة دفع',             'Show Payment Method'],
        'payment_method_delete'       => ['حذف طريقة دفع',             'Delete Payment Method'],
        'payment_method_access'       => ['الوصول لطرق الدفع',         'Access Payment Methods'],
        'subscription_package_create' => ['إضافة باقة اشتراك',         'Create Subscription Package'],
        'subscription_package_edit'   => ['تعديل باقة اشتراك',         'Edit Subscription Package'],
        'subscription_package_show'   => ['عرض باقة اشتراك',           'Show Subscription Package'],
        'subscription_package_delete' => ['حذف باقة اشتراك',           'Delete Subscription Package'],
        'subscription_package_access' => ['الوصول لباقات الاشتراك',    'Access Subscription Packages'],
        'subscription_access'         => ['الوصول للاشتراكات',         'Access Subscriptions'],
        'subscription_vip_create'     => ['إضافة اشتراك VIP',          'Create VIP Subscription'],
        'subscription_vip_edit'       => ['تعديل اشتراك VIP',          'Edit VIP Subscription'],
        'subscription_vip_show'       => ['عرض اشتراك VIP',            'Show VIP Subscription'],
        'subscription_vip_delete'     => ['حذف اشتراك VIP',            'Delete VIP Subscription'],
        'subscription_vip_access'     => ['الوصول لاشتراكات VIP',      'Access VIP Subscriptions'],
        'subscription_user_create'    => ['إضافة اشتراك مستخدم',       'Create User Subscription'],
        'subscription_user_edit'      => ['تعديل اشتراك مستخدم',       'Edit User Subscription'],
        'subscription_user_show'      => ['عرض اشتراك مستخدم',         'Show User Subscription'],
        'subscription_user_delete'    => ['حذف اشتراك مستخدم',         'Delete User Subscription'],
        'subscription_user_access'    => ['الوصول لاشتراكات المستخدمين','Access User Subscriptions'],
        'coupon_create'               => ['إضافة كوبون',               'Create Coupon'],
        'coupon_edit'                 => ['تعديل كوبون',               'Edit Coupon'],
        'coupon_show'                 => ['عرض كوبون',                 'Show Coupon'],
        'coupon_delete'               => ['حذف كوبون',                 'Delete Coupon'],
        'coupon_access'               => ['الوصول للكوبونات',          'Access Coupons'],
        // ── Locations (cat 7) ────────────────────────────────────────────────
        'country_create'              => ['إضافة دولة',                'Create Country'],
        'country_edit'                => ['تعديل دولة',                'Edit Country'],
        'country_show'                => ['عرض دولة',                  'Show Country'],
        'country_delete'              => ['حذف دولة',                  'Delete Country'],
        'country_access'              => ['الوصول للدول',              'Access Countries'],
        'city_create'                 => ['إضافة مدينة',               'Create City'],
        'city_edit'                   => ['تعديل مدينة',               'Edit City'],
        'city_show'                   => ['عرض مدينة',                 'Show City'],
        'city_delete'                 => ['حذف مدينة',                 'Delete City'],
        'city_access'                 => ['الوصول للمدن',              'Access Cities'],
        'currency_create'             => ['إضافة عملة',                'Create Currency'],
        'currency_edit'               => ['تعديل عملة',                'Edit Currency'],
        'currency_show'               => ['عرض عملة',                  'Show Currency'],
        'currency_delete'             => ['حذف عملة',                  'Delete Currency'],
        'currency_access'             => ['الوصول للعملات',            'Access Currencies'],
        'place_access'                => ['الوصول للأماكن',            'Access Places'],
        // ── Ads (cat 8) ──────────────────────────────────────────────────────
        'ad_access'                   => ['الوصول للإعلانات',          'Access Ads'],
        'ads_category_create'         => ['إضافة تصنيف إعلانات',       'Create Ads Category'],
        'ads_category_edit'           => ['تعديل تصنيف إعلانات',       'Edit Ads Category'],
        'ads_category_show'           => ['عرض تصنيف إعلانات',         'Show Ads Category'],
        'ads_category_delete'         => ['حذف تصنيف إعلانات',         'Delete Ads Category'],
        'ads_category_access'         => ['الوصول لتصنيفات الإعلانات', 'Access Ads Categories'],
        'all_ad_create'               => ['إضافة إعلان',               'Create Ad'],
        'all_ad_edit'                 => ['تعديل إعلان',               'Edit Ad'],
        'all_ad_show'                 => ['عرض إعلان',                 'Show Ad'],
        'all_ad_delete'               => ['حذف إعلان',                 'Delete Ad'],
        'all_ad_access'               => ['الوصول لجميع الإعلانات',    'Access All Ads'],
        // ── Support & Tickets (cat 9) ─────────────────────────────────────────
        'ticket_create'               => ['إضافة تذكرة دعم',           'Create Ticket'],
        'ticket_edit'                 => ['تعديل تذكرة دعم',           'Edit Ticket'],
        'ticket_show'                 => ['عرض تذكرة دعم',             'Show Ticket'],
        'ticket_delete'               => ['حذف تذكرة دعم',             'Delete Ticket'],
        'ticket_access'               => ['الوصول للتذاكر',            'Access Tickets'],
        'ticketmanagement_access'     => ['إدارة التذاكر',             'Ticket Management'],
        'ticket_status_create'        => ['إضافة حالة تذكرة',          'Create Ticket Status'],
        'ticket_status_edit'          => ['تعديل حالة تذكرة',          'Edit Ticket Status'],
        'ticket_status_show'          => ['عرض حالة تذكرة',            'Show Ticket Status'],
        'ticket_status_delete'        => ['حذف حالة تذكرة',            'Delete Ticket Status'],
        'ticket_status_access'        => ['الوصول لحالات التذاكر',     'Access Ticket Statuses'],
        'faq_create'                  => ['إضافة سؤال شائع',           'Create FAQ'],
        'faq_edit'                    => ['تعديل سؤال شائع',           'Edit FAQ'],
        'faq_show'                    => ['عرض سؤال شائع',             'Show FAQ'],
        'faq_delete'                  => ['حذف سؤال شائع',             'Delete FAQ'],
        'faq_access'                  => ['الوصول للأسئلة الشائعة',    'Access FAQs'],
        // ── Points (cat 10) ──────────────────────────────────────────────────
        'point_create'                => ['إضافة نقطة',                'Create Point'],
        'point_edit'                  => ['تعديل نقطة',                'Edit Point'],
        'point_show'                  => ['عرض نقطة',                  'Show Point'],
        'point_delete'                => ['حذف نقطة',                  'Delete Point'],
        'point_access'                => ['الوصول للنقاط',             'Access Points'],
        'point_management_access'     => ['إدارة النقاط',              'Point Management'],
        'point_type_create'           => ['إضافة نوع نقطة',            'Create Point Type'],
        'point_type_edit'             => ['تعديل نوع نقطة',            'Edit Point Type'],
        'point_type_show'             => ['عرض نوع نقطة',              'Show Point Type'],
        'point_type_delete'           => ['حذف نوع نقطة',              'Delete Point Type'],
        'point_type_access'           => ['الوصول لأنواع النقاط',      'Access Point Types'],
        // ── Cars (cat 11) ────────────────────────────────────────────────────
        'car_access'                  => ['الوصول للسيارات',           'Access Cars'],
        'carbrand_create'             => ['إضافة ماركة سيارة',         'Create Car Brand'],
        'carbrand_edit'               => ['تعديل ماركة سيارة',         'Edit Car Brand'],
        'carbrand_show'               => ['عرض ماركة سيارة',           'Show Car Brand'],
        'carbrand_delete'             => ['حذف ماركة سيارة',           'Delete Car Brand'],
        'carbrand_access'             => ['الوصول لماركات السيارات',   'Access Car Brands'],
        'type_of_car_create'          => ['إضافة نوع سيارة',           'Create Car Type'],
        'type_of_car_edit'            => ['تعديل نوع سيارة',           'Edit Car Type'],
        'type_of_car_show'            => ['عرض نوع سيارة',             'Show Car Type'],
        'type_of_car_delete'          => ['حذف نوع سيارة',             'Delete Car Type'],
        'type_of_car_access'          => ['الوصول لأنواع السيارات',    'Access Car Types'],
        'car_color_create'            => ['إضافة لون سيارة',           'Create Car Color'],
        'car_color_edit'              => ['تعديل لون سيارة',           'Edit Car Color'],
        'car_color_show'              => ['عرض لون سيارة',             'Show Car Color'],
        'car_color_delete'            => ['حذف لون سيارة',             'Delete Car Color'],
        'car_color_access'            => ['الوصول لألوان السيارات',    'Access Car Colors'],
        'car_list_create'             => ['إضافة سيارة',               'Create Car'],
        'car_list_edit'               => ['تعديل سيارة',               'Edit Car'],
        'car_list_show'               => ['عرض سيارة',                 'Show Car'],
        'car_list_delete'             => ['حذف سيارة',                 'Delete Car'],
        'car_list_access'             => ['الوصول لقائمة السيارات',    'Access Car List'],
        // ── Notifications (cat 12) ───────────────────────────────────────────
        'notification_create'         => ['إضافة إشعار',               'Create Notification'],
        'notification_edit'           => ['تعديل إشعار',               'Edit Notification'],
        'notification_show'           => ['عرض إشعار',                 'Show Notification'],
        'notification_delete'         => ['حذف إشعار',                 'Delete Notification'],
        'notification_access'         => ['الوصول للإشعارات',          'Access Notifications'],
        'user_alert_create'           => ['إضافة تنبيه مستخدم',        'Create User Alert'],
        'user_alert_show'             => ['عرض تنبيه مستخدم',          'Show User Alert'],
        'user_alert_delete'           => ['حذف تنبيه مستخدم',          'Delete User Alert'],
        'user_alert_access'           => ['الوصول لتنبيهات المستخدمين','Access User Alerts'],
        // ── Other (cat 13) ───────────────────────────────────────────────────
        'sitting_area_create'         => ['إضافة منطقة جلوس',          'Create Sitting Area'],
        'sitting_area_edit'           => ['تعديل منطقة جلوس',          'Edit Sitting Area'],
        'sitting_area_show'           => ['عرض منطقة جلوس',            'Show Sitting Area'],
        'sitting_area_delete'         => ['حذف منطقة جلوس',            'Delete Sitting Area'],
        'sitting_area_access'         => ['الوصول لمناطق الجلوس',      'Access Sitting Areas'],
        'reporting_create'            => ['إضافة تقرير',               'Create Report'],
        'reporting_edit'              => ['تعديل تقرير',               'Edit Report'],
        'reporting_show'              => ['عرض تقرير',                 'Show Report'],
        'reporting_delete'            => ['حذف تقرير',                 'Delete Report'],
        'reporting_access'            => ['الوصول للتقارير',           'Access Reports'],
        'rate_create'                 => ['إضافة تقييم',               'Create Rate'],
        'rate_edit'                   => ['تعديل تقييم',               'Edit Rate'],
        'rate_show'                   => ['عرض تقييم',                 'Show Rate'],
        'rate_delete'                 => ['حذف تقييم',                 'Delete Rate'],
        'rate_access'                 => ['الوصول للتقييمات',          'Access Rates'],
        'cart_create'                 => ['إضافة سلة',                 'Create Cart'],
        'cart_edit'                   => ['تعديل سلة',                 'Edit Cart'],
        'cart_show'                   => ['عرض سلة',                   'Show Cart'],
        'cart_delete'                 => ['حذف سلة',                   'Delete Cart'],
        'cart_access'                 => ['الوصول للسلة',              'Access Carts'],
        'address_create'              => ['إضافة عنوان',               'Create Address'],
        'address_edit'                => ['تعديل عنوان',               'Edit Address'],
        'address_show'                => ['عرض عنوان',                 'Show Address'],
        'address_delete'              => ['حذف عنوان',                 'Delete Address'],
        'address_access'              => ['الوصول للعناوين',           'Access Addresses'],
        'save_credit_card_create'     => ['حفظ بطاقة ائتمان',          'Save Credit Card'],
        'save_credit_card_edit'       => ['تعديل بطاقة ائتمان',        'Edit Credit Card'],
        'save_credit_card_show'       => ['عرض بطاقة ائتمان',          'Show Credit Card'],
        'save_credit_card_delete'     => ['حذف بطاقة ائتمان',          'Delete Credit Card'],
        'save_credit_card_access'     => ['الوصول لبطاقات الائتمان',   'Access Credit Cards'],
        'favorite_create'             => ['إضافة مفضلة',               'Create Favorite'],
        'favorite_edit'               => ['تعديل مفضلة',               'Edit Favorite'],
        'favorite_show'               => ['عرض مفضلة',                 'Show Favorite'],
        'favorite_delete'             => ['حذف مفضلة',                 'Delete Favorite'],
        'favorite_access'             => ['الوصول للمفضلة',            'Access Favorites'],
        'onbordering_create'          => ['إضافة تأهيل',               'Create Onboarding'],
        'onbordering_edit'            => ['تعديل تأهيل',               'Edit Onboarding'],
        'onbordering_show'            => ['عرض تأهيل',                 'Show Onboarding'],
        'onbordering_delete'          => ['حذف تأهيل',                 'Delete Onboarding'],
        'onbordering_access'          => ['الوصول للتأهيل',            'Access Onboarding'],
        'table_create'                => ['إضافة طاولة',               'Create Table'],
        'table_edit'                  => ['تعديل طاولة',               'Edit Table'],
        'table_show'                  => ['عرض طاولة',                 'Show Table'],
        'table_delete'                => ['حذف طاولة',                 'Delete Table'],
        'table_access'                => ['الوصول للطاولات',           'Access Tables'],
        'table_status_create'         => ['إضافة حالة طاولة',          'Create Table Status'],
        'table_status_edit'           => ['تعديل حالة طاولة',          'Edit Table Status'],
        'table_status_show'           => ['عرض حالة طاولة',            'Show Table Status'],
        'table_status_delete'         => ['حذف حالة طاولة',            'Delete Table Status'],
        'table_status_access'         => ['الوصول لحالات الطاولات',    'Access Table Statuses'],
        'otherbranch_create'          => ['إضافة فرع آخر',             'Create Other Branch'],
        'otherbranch_edit'            => ['تعديل فرع آخر',             'Edit Other Branch'],
        'otherbranch_show'            => ['عرض فرع آخر',               'Show Other Branch'],
        'otherbranch_delete'          => ['حذف فرع آخر',               'Delete Other Branch'],
        'otherbranch_access'          => ['الوصول للفروع الأخرى',      'Access Other Branches'],
        'profile_password_edit'       => ['تعديل كلمة المرور',         'Edit Profile Password'],
    ];

    public function handle(): int
    {
        $updated = 0;

        Permission::withTrashed()->chunkById(100, function ($perms) use (&$updated) {
            foreach ($perms as $perm) {
                $key = $perm->title;
                if (!isset($this->map[$key])) continue;

                [$ar, $en] = $this->map[$key];

                $needsUpdate = empty($perm->name_ar) || empty($perm->name_en);
                if ($needsUpdate) {
                    $perm->name_ar = $ar;
                    $perm->name_en = $en;
                    $perm->save();
                    $updated++;
                }
            }
        });

        $this->info("✅ Updated {$updated} permissions.");
        return 0;
    }
}
